### PR TITLE
Implement `default_headers` option for Absinthe.Plug.GraphiQL

### PR DESCRIPTION
**Pull request by petejkim**
Implement `default_headers` option for [Absinthe.Plug.GraphiQL (#76)](https://github.com/absinthe-graphql/absinthe_plug/issues/76)

--- 

```elixir
forward "/graphiql",
  Absinthe.Plug.GraphiQL,
  schema: MyApp.Schema,
  default_headers: {__MODULE__, :graphiql_headers}

def graphiql_headers do
  %{
    "X-CSRF-Token" => Plug.CSRFProtection.get_csrf_token(),
    "X-Foo" => "Bar"
  }
end
```

screen shot 2017-04-21 at 12 56 02 am

### CODE REVIEW

**Comment by petejkim** [comment]
Any comments?

**Comment by bruce** [comment]
This looks really good to me; thank you for including docs and a test (and fixing that README merge issue, oops). Merging.

**Comment by bruce** [comment]
Released in v1.3.1. Thank you again.

**Comment by petejkim** [comment]
Thanks!

**Comment by tapajos** [comment]
Looks like it doesn't work when using `interface: :playground`.

**Pull request merged**
