### PR TITLE
Set all plug options via put_options

### LINKED ISSUE #241: Dynamically generated max complexity
Hello! 👋 First of all, thank you for Absinthe and `Absinthe.Plug`!

I'm wondering if the maintainers would be open to the addition of a feature to dynamically determine the max complexity per query. I'd like to be able to say something like, "User X made a query, they have Y complexity allowance left, will I allow them to make this query?"

Of course this doesn't match the primary use case. 😄 

Whereas the current API looks like this:

```elixir
plug Absinthe.Plug,
  schema: MyAppWeb.Schema,
  analyze_complexity: true,
  max_complexity: 50
```

I would like to propose expanding the API to support this as well:

```elixir
plug Absinthe.Plug,
  schema: MyAppWeb.Schema,
  analyze_complexity: true,
  max_complexity: &MyModule.max_complexity/1
```

Where `&MyModule.max_complexity/1` is a function that is given the context and query and returns back an integer.

Thank you for considering! I would be glad to whip up a PR if you're open to this. Cheers!

### PR DESCRIPTION
**Pull request by binaryseed**
This PR wires up the ability to set complexity settings via `put_options`

@benwilson512 These make sense to set on a per-request basis, but I'm not sure if the other options do...

closes #241

### CODE REVIEW

**Comment by benwilson512** [comment]
@binaryseed Looking through the options list, I could imagine almost all of them being relevant based on different headers or something. Adapters, whether you have before_send, I think literally all of them could be relevantly different based on client header or path values.

**Comment by binaryseed** [comment]
Ok, wired it up, mind giving it a quick review?

**Review by benwilson512 — APPROVED** [review]
Looks great!

**Comment by binaryseed** [comment]
Released in `1.5.4`

**Pull request merged**
