### PR TITLE
Use erlef/setup-beam for GitHub Actions

### PR DESCRIPTION
**Pull request by kianmeng**

### CODE REVIEW

**Comment by benwilson512** [comment]
Hey @kianmeng this seems good, but I also don't really know a lot about this change. Can you elaborate on what this accomplishes?

**Comment by kianmeng** [comment]
@benwilson512 https://github.com/erlef/setup-elixir redirects to https://github.com/erlef/setup-beam.

**Comment by benwilson512** [comment]
Great, thanks!

**Comment by kianmeng** [comment]
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face:

**Pull request merged**
