### PR TITLE
Playground update

### PR DESCRIPTION
**Pull request by benwilson512**
@tlvenn I tried running this locally but couldn't get subscriptions to work, it was simply submitting subscriptions via HTTP.

### CODE REVIEW

**Comment by tlvenn** [comment]
Ya noticed this as well @benwilson512 , will update to latest version and fix subscription this coming week. I keep you posted.

**Comment by benwilson512** [comment]
Thanks!

**Comment by JonRowe** [comment]
Hi, I'd like to attempt to get this working, as the newest version of GraphQL playground contains support for default headers, but I can't even get the asset to update, am I doing something wrong other than just changing the file to match?

**Comment by fredr** [comment]
It would be nice to get the playground up to version 1.8.x, since the share functionality is broken before that (fixed in https://github.com/prisma/graphql-playground/pull/847).

I can have a look, but I guess we first need to bump https://github.com/absinthe-graphql/absinthe-graphql-playground to use 1.8.x

**Comment by fredr** [comment]
Should work after this is merged: https://github.com/absinthe-graphql/absinthe-graphql-playground/pull/2

**Comment by tlvenn** [comment]
Thanks for the contribution @fredr ! I will publish the new version of our custom playground and will update absinthe-plug later today.

**Comment by bruce** [comment]
@tlvenn Is this related to #199?

**Comment by jfrolich** [comment]
This fixes #199 for me.

**Comment by DMeechan** [comment]
Is the update to GraphQL Playground available? I'm having issues with the Share button too, like @fredr mentioned above.

I'm running `absinthe 1.4.16`, `absinthe_phoenix 1.4.3`, and `absinthe_plug 1.4.6`

**Comment by binaryseed** [comment]
Howdy folks, is this ticket still relevant?

**Comment by JonRowe** [comment]
@binaryseed if the vendored version of playground has not been updated then, yes, very much so..

**Comment by binaryseed** [comment]
Closing this particular ticket since this is quite stale, and our path forward is to remove GraphiQL from `Absinthe.Plug`...

**Pull request closed without merging**
