### PR TITLE
Fix minor stuff (and add dialyxir to CI)

### PR DESCRIPTION
**Pull request by paulo-ferraz-oliveira**
The individual commits are presented in a way that their content should help with the review.

The Dialyzer issues we'll see are fixed by changes in [another pull request](https://github.com/absinthe-graphql/absinthe/pull/1248) (**edit**: ... which means I can pull that in once/if it's approved+merged+tag/released).

### CODE REVIEW

**Comment by paulo-ferraz-oliveira** [comment]
@benwilson512, is there a chance this gets reviewed? Thanks.

**Comment by paulo-ferraz-oliveira** [comment]
Ah, this still needs the `absinthe` tag/release to be effective (otherwise it won't fetch the new dep.).

**Comment by benwilson512** [comment]
Got it. Let me get that out here shortly.

**Comment by paulo-ferraz-oliveira** [comment]
@benwilson512, anything I can do to help unblocked that release/tag? (we're so close 😄)

**Comment by benwilson512** [comment]
v1.7.2 of Absinthe has been published.

**Comment by paulo-ferraz-oliveira** [comment]
Force pushed to resolve merge conflicts...

**Comment by paulo-ferraz-oliveira** [comment]
I'm gonna adapt this lib.s base versions (Elixir + Erlang) to what `absinthe`'s using.

**Comment by paulo-ferraz-oliveira** [comment]
CI results at https://github.com/paulo-ferraz-oliveira/absinthe_plug/actions/runs/5426470445

**Comment by benwilson512** [comment]
Thanks!

**Pull request merged**
