### PR TITLE
Add Altair GraphQL interface.

### PR DESCRIPTION
**Pull request by imolorhe**
This PR introduces the [Altair GraphQL](https://altair.sirmuel.design/) interface, as an alternative to GraphiQL and GraphQL playground.

Altair is a more fully featured alternative to the other options and has become a household name for working with GraphQL. It also seems to not suffer from issues affecting other tools (e.g. #199).

Please review and let me know what you think! 😊

### CODE REVIEW

**Comment by smaximov** [comment]
Thanks for the PR, @imolorhe, I looked up Altair and it looks great! I also like that it's apparently more maintained than the alternatives.

I have a small request: can you also add support for [`:default_headers`](https://hexdocs.pm/absinthe_plug/1.5.0-rc.0/Absinthe.Plug.GraphiQL.html#module-default-headers) similar to how it is done for GraphiQL Workspace? According to the [README](https://github.com/imolorhe/altair#configuration-options), Altair supports it as the `initialHeaders` configuration option.

**Comment by imolorhe** [comment]
@smaximov I wouldn't mind adding it. However, I'm not conversant enough with elixir to know the right way to pass a dictionary type (GraphiQL seems to use headers as an array, but Altair uses a dictionary/map/object type). If you can give me a pointer in the right direction, I wouldn't mind adding that. 🙂

**Comment by smaximov** [comment]
@imolorhe I believe you should just encode it as JSON. This is done in `handle_default_headers` for GraphiQL Workspace:

https://github.com/absinthe-graphql/absinthe_plug/blob/fc938660a393c1b5f9c4eef46a83dfff3b19d1e0/lib/absinthe/plug/graphiql.ex#L407-L411

The trick is to select the correct headers representation depending on the configured interface. Something like this should do:

``` elixir
  defp handle_default_headers(%{interface: interface} = config, conn) do
    default_headers =
      case get_config_val(config, :default_headers, conn) do
        nil ->
          {}

        val when is_map(val) ->
          val

        val ->
          raise "invalid default headers: #{inspect(val)}"
      end

    header_string =
      default_headers
      |> prepare_default_headers(interface)
      |> config.json_codec.module.encode!(pretty: true)

    Map.put(config, :default_headers, header_string)
  end
  
  # headers will be encoded as an array of objects (for Playground)
  defp prepare_default_headers(headers, :advanced),
    do: Enum.map(headers, fn {k, v} -> %{"name" => k, "value" => v} end)

  # headers will be encoded as an object (for Altair)
  defp prepare_default_headers(headers, :altair), do: headers

  # fail if unsupported interface is configured
  defp prepare_default_headers(_headers, interface),
    do: raise(":default_headers option not supported for interface #{inspect(interface)}")
```

Please tell me if you need help with it.

**Comment by benwilson512** [comment]
Hi @imolorhe thanks for the PR. It is my sense that adding additional GraphiQL UIs is not the way to go, in fact in a future version of `absinthe_plug` I'd prefer to include NO GraphiQL interfaces (or maybe just the "standard" one) and instead have each different interface provided as a distinct package.

There are dozens of GraphiQL like clients out there and it just isn't feasible to have the core team maintain all of them. I don't see anything here in this PR that couldn't be provided by an external library and maintained by those who care about it most. @bruce thoughts?

**Comment by bruce** [comment]
@benwilson512 I agree. Altair is my favorite GraphQL client, but as we’ve discovered with our current packaged clients, it is very difficult to stay up-to-date with releases and manage issues with CDNs over time while maintaining our focus on Absinthe itself.

@imolorhe Please don’t be discouraged by our resistance to including this. I think this idea would make a great third-party package that we’d be happy to link to in docs. The decision really has more to do with us trying to keep Absinthe’s project scope focused—it’s already quite a bit for us maintainers to take care of and improve.

**Comment by imolorhe** [comment]
Alright then

**Comment by imolorhe** [comment]
I can't seem to close the PR. Feel free to close it.

**Pull request closed without merging**
