### PR TITLE
Enabling support to `_json` to no batched requests;

### PR DESCRIPTION
**Pull request by gullitmiranda**
fix #98

### CODE REVIEW

**Comment by benwilson512** [comment]
Hey! Thanks for the PR. Unfortunately I don't really understand what you're trying to accomplish here. You reference #98 but that's also a PR. Why the `_json` key be used?

**Comment by gullitmiranda** [comment]
hi @benwilson512.

with a small adjustment (which I'll do PR later) in the lib https://github.com/jaydenseric/apollo-upload-client it is possible to make submissions of data without problems.

the changes in this PR is to make the behavior of not batched queries also support the `_json`. So the data are sent in the correct form, for send parameters (especially with depth properties) causes several problems and has many limitations.

example of data to be sent that does not work correctly:

```js
{
  works: ["value1", "value2"],
  withTricksWork: {
    data: "value",
    array: ["..."]
  },

  arrayWithObjectWithMultipleKeysNotWork: [{ k1: "v1", k2: "v2"}, { k2: "v2", k1: "v1"}, ...]
}
```

**Comment by benwilson512** [comment]
My question is, why are not batched queries using `_json` param. at all and not the standard `query` and `variables` param?

**Comment by gullitmiranda** [comment]
1. why my application is not yet using batched query.
2. Because for the upload it is necessary to send through the multi-part the that has limitations to parsing and serialization.
3. If batched queries support `_json` why not batched queries also does not support, thus maintaining the standard.

**Comment by benwilson512** [comment]
The issue is there is already a standard for non batching multipart. You use `query` for the query and `variables` for variables, that way it's basically the same as regular POST or GET.

`_json` isn't really a standard, and in fact the PR you linked to provides "operations" because other than phoenix, it isn't really a normal thing to use.

I suppose my main question is, if you aren't batching, why can't you do 2 + n parts:
```
-- PART1--
query=mutation ($upload: Upload!) { upload(file: $file) }
variables={"upload":"foo"}
foo=#<file contents>
```

**Comment by gullitmiranda** [comment]
because de struct is some complex:

Dump of one my forms:
```
------WebKitFormBoundaryaTjxcVRmzSxSmQBy
Content-Disposition: form-data; name="_json"

{"query":"mutation CreateDocument($input: CreateDocumentInput!) {\n  createDocument(input: $input) {\n    clientMutationId\n    document {\n      id\n      insertedAt\n      __typename\n    }\n    __typename\n  }\n}\n","variables":{"input":{"clientMutationId":"createDocument:rg-e-cpf","content":"{\"rgFront\":{\"Número\":\"9839843748723\",\"Data de expedição\":\"2017-08-30\"},\"rgBack\":{\"Orgão emissor\":\"SSP\",\"Estado de emissão\":\"SP\"},\"cpf\":\"123.123.123-55\"}","attachments":[{"attachment":"input.attachments.0.attachment","fragment":"rgFront","contentType":"image/png"},{"attachment":"input.attachments.1.attachment","fragment":"rgBack","contentType":"image/png"},{"attachment":"input.attachments.2.attachment","fragment":"cpf","contentType":"image/png"}],"employeeId":"RW1wbG95ZWU6YTMzNmViMmQtMDg1OS00ZGVhLWJjNTgtNDg4MGFkN2I1YWE5","companyId":"Q29tcGFueTo3MmM2OTgwZi0zYzYyLTRkYjQtYTg0MS1mYzE4M2VmMDgyMDg=","key":"rg-e-cpf","completed":100,"status":"VALIDATION"}},"operationName":"CreateDocument"}
------WebKitFormBoundaryaTjxcVRmzSxSmQBy
Content-Disposition: form-data; name="input.attachments.0.attachment"; filename="RG.png"
Content-Type: image/png


------WebKitFormBoundaryaTjxcVRmzSxSmQBy
Content-Disposition: form-data; name="input.attachments.1.attachment"; filename="RG.png"
Content-Type: image/png


------WebKitFormBoundaryaTjxcVRmzSxSmQBy
Content-Disposition: form-data; name="input.attachments.2.attachment"; filename="RG.png"
Content-Type: image/png


------WebKitFormBoundaryaTjxcVRmzSxSmQBy--
```

**Comment by benwilson512** [comment]
Sure, but why can't you do something like this:
```
------WebKitFormBoundaryaTjxcVRmzSxSmQBy
Content-Disposition: form-data; name="query"
mutation CreateDocument($input: CreateDocumentInput!) {
  createDocument(input: $input) {
    clientMutationId
    document {
      id
      insertedAt
      __typename
    }
    __typename
  }
}


------WebKitFormBoundaryaTjxcVRmzSxSmQBy
Content-Disposition: form-data; name="query"
Content-Type: application/json
{"input":{"clientMutationId":"createDocument:rg-e-cpf","content":"{\"rgFront\":{\"Número\":\"9839843748723\",\"Data de expedição\":\"2017-08-30\"},\"rgBack\":{\"Orgão emissor\":\"SSP\",\"Estado de emissão\":\"SP\"},\"cpf\":\"123.123.123-55\"}","attachments":[{"attachment":"input.attachments.0.attachment","fragment":"rgFront","contentType":"image/png"},{"attachment":"input.attachments.1.attachment","fragment":"rgBack","contentType":"image/png"},{"attachment":"input.attachments.2.attachment","fragment":"cpf","contentType":"image/png"}],"employeeId":"RW1wbG95ZWU6YTMzNmViMmQtMDg1OS00ZGVhLWJjNTgtNDg4MGFkN2I1YWE5","companyId":"Q29tcGFueTo3MmM2OTgwZi0zYzYyLTRkYjQtYTg0MS1mYzE4M2VmMDgyMDg=","key":"rg-e-cpf","completed":100,"status":"VALIDATION"}}


------WebKitFormBoundaryaTjxcVRmzSxSmQBy
Content-Disposition: form-data; name="input.attachments.0.attachment"; filename="RG.png"
Content-Type: image/png


------WebKitFormBoundaryaTjxcVRmzSxSmQBy
Content-Disposition: form-data; name="input.attachments.1.attachment"; filename="RG.png"
Content-Type: image/png


------WebKitFormBoundaryaTjxcVRmzSxSmQBy
Content-Disposition: form-data; name="input.attachments.2.attachment"; filename="RG.png"
Content-Type: image/png


------WebKitFormBoundaryaTjxcVRmzSxSmQBy--
```

`_json` isn't a standard, I would like to move away from it completely. `query` and `variables` is.

**Pull request closed without merging**
