### PR TITLE
Corrected syntax for Plug's forward macro

### PR DESCRIPTION
**Pull request by rawkode**

### CODE REVIEW

**Comment by bruce** [comment]
Hmmm.. the following is working just fine in projects we have on Phoenix 1.3 and 1.2.X:

```
forward "/api", Absinthe.Plug,
  schema: OurWeb.Schema,
  # other options
```

The Phoenix docs [also omit](https://hexdocs.pm/phoenix/Phoenix.Router.html#forward/4-examples) a `:to` option.

**Comment by rawkode** [comment]
Hi @bruce, I'm not using Phoenix. Plug requires the `to:`

https://hexdocs.pm/plug/Plug.Router.html#forward/2

**Comment by bruce** [comment]
Right, okay. We're going to have to explicitly lay it out for each, probably; my concern here is most people are using Phoenix and just copy this code out wholesale.

**Comment by rawkode** [comment]
@bruce Yeah, most people will come from Phoenix and won't encounter this issue.

Perhaps just a warning: "If you're not using Phoenix, this syntax will not work. Please consult https://hexdocs.pm/plug/ ?"

**Comment by yordis** [comment]
@bruce @rawkode hah I see why didn't work the first time for me, I was using `Plug` way and I didn't understand why was failing.

@bruce there is some `absinthe_phoenix` wouldn't be better to add the phoenix case there?

**Comment by benwilson512** [comment]
This has been handled in master.

**Pull request closed without merging**
