### PR TITLE
allow to set default query

### PR DESCRIPTION
**Pull request by ayrat555**
Changelog:
- allow passing `default_query` parameter to `advanced` GraphiQL interface

### CODE REVIEW

**Comment by ayrat555** [comment]
@benwilson512 @bruce can you take a look when you have time? thanks

**Comment by ayrat555** [comment]
@benwilson512 ping

**Comment by ayrat555** [comment]
@bruce you're my only hope!

**Comment by axelson** [comment]
@ayrat555 just curious, what is the point of passing a `default_query`? i.e. what does it do? What is a typical use-case. Also I would think that it would be best to support the basic graphiql as well as advanced.

**Comment by ayrat555** [comment]
@axelson to show it as an example in the graphiql interface. `playground` does not support passing default query. There is an issue https://github.com/prisma/graphql-playground/issues/301

**Comment by benwilson512** [comment]
Hi @ayrat555, please use `mix format` so that the CI passes.

**Comment by ayrat555** [comment]
@benwilson512 done

**Comment by ayrat555** [comment]
@benwilson512 will you merge it?

**Comment by ayrat555** [comment]
thanks!

**Pull request merged**
